# Configuration for the training process

# Model Parameters
model_params:
  name: "resnet18"
  num_classes: 2
  pretrained: true

# Data Parameters
data_params:
  data_path: "chest_xray/" # Relative to project root
  batch_size: 16
  num_workers: 0 # Number of CPU cores to use for data loading

# Trainer Parameters
trainer_params:
  max_epochs: 3
  learning_rate: 0.0001 # 1e-4
  use_weighted_loss: true
  accelerator: "auto" # Will auto-detect 'gpu' if available, otherwise 'cpu'